language: php

dist: bionic
sudo: required

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      - chromium-chromedriver
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    #    - php: 7.3 # Master build not currently reliable following the JS build changes.
    #      env:
    #      - MOODLE_BRANCH=master
    #      - DB=pgsql

    - php: 7.3
      env:
        - MOODLE_BRANCH=MOODLE_37_STABLE
        - DB=mysqli

    - php: 7.2
      env:
        - MOODLE_BRANCH=MOODLE_37_STABLE
        - DB=mysqli

    - php: 7.1
      env:
        - MOODLE_BRANCH=MOODLE_36_STABLE
        - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd || true      # report issues, but don't fail the build.
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker || true # It currently fails to cope with PHP 7.1 return type hints.
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true    # report issues, but don't fail the build. Current issue contacting the validator.
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --profile chrome
